### ISSUE TITLE
Finish 1.2.18 release

### ISSUE THREAD

**Issue by dwijnand** [coursier/sbt-launcher#117]
Looks like the 1.2.18 release failed, so it's no consumable from sbt-extras: https://travis-ci.org/coursier/sbt-launcher/jobs/614999713.

Could you fix it, do you think?  I'd like to consume the dependency graph fixes 😄

Thanks!

**Comment by alexarchambault** [comment]
@dwijnand Thanks, it's on its way!

**Comment by dwijnand** [comment]
Wonderful, thank you: https://github.com/coursier/sbt-launcher/releases/tag/v1.2.18.
