### ISSUE TITLE
Doesn't support sbt-dependency-graph?

### ISSUE THREAD

**Issue by dwijnand** [coursier/sbt-launcher#38]
It looks like when using this launcher sbt-dependency-graph doesn't have access to the information it's looking for.  So, for instance, `dependencyTree` shows no dependencies.

If you can't reproduce, I'll try and put together a minimal reproduction.

**Comment by dwijnand** [comment]
Just reproduced.  Check out https://github.com/scalacommunitybuild/akka-persistence-jdbc/tree/community-build-2.13 and use coursier/sbt-extras.

```
> projects
[info] In file:/d/akka-persistence-jdbc/
[info] 	 * akka-persistence-jdbc
> dependencyTree
[info] com.github.dnvriend:akka-persistence-jdbc_2.12:3.6.0-SNAPSHOT
[success] Total time: 0 s, completed 15-May-2019 07:18:09
```

**Comment by dwijnand** [comment]
Using regular sbt-extras and sbt-launcher:

```
> dependencyTree
[info] com.github.dnvriend:akka-persistence-jdbc_2.12:3.6.0-SNAPSHOT [S]
[info]   +-com.typesafe.akka:akka-actor_2.12:2.5.22 [S]
[info]   | +-com.typesafe:config:1.3.3
[info]   | +-org.scala-lang.modules:scala-java8-compat_2.12:0.8.0 [S]
[info]   |
[info]   +-com.typesafe.akka:akka-persistence-query_2.12:2.5.22 [S]
etc etc
```

**Comment by alexarchambault** [comment]
Seems it's an issue with the sbt-lm-coursier plugin, that the launcher adds automatically. I opened https://github.com/coursier/coursier/issues/1170 for it, so closing this one.

There's no issue with sbt-coursier on the other hand, so it can be forced as a workaround, like:
```
$ sbt -C--coursier-plugin=sbt-coursier dependencyTree
```
